### ISSUE TITLE
Similar search terms overlap

### ISSUE THREAD

**Issue by Zeioth** [Zeioth/rofi-zeal#3]
Let's say I search 

    python:print

and then I search 

    python:pr

rofi-zeal won't let you search the second term, and the first one will be selected instead. This is a minor issue, but PR are welcome.

**Comment by Zeioth** [comment]
Search log limited to 20 until there's a solution (which rofi doesn't currently provide).

**Comment by rixx** [comment]
This kind of makes it impossible to first open a term in one mode, say zeal, and then in another mode, like stackoverflow :/

**Comment by Zeioth** [comment]
I agree. I'm gonna disable the history entirely on V2. Making it 100% bug free is more important than having a history, which rofi can't provide for this case of use.

**Comment by Zeioth** [comment]
History disabled
