### ISSUE TITLE
PKGBUILD doesn't track files

### ISSUE THREAD

**Issue by WillForan** [Zeioth/rofi-zeal#5]
`pacman -Ql rofi-zeal-git` is empty; package files aren't tracked.  Only the user running `makepkg` gets `rofi-zeal`

maybe `install -Dm755 rofi-zeal /usr/bin/` instead of symlinking to ~/.local/bin

**Comment by Zeioth** [comment]
Thank you for reporting. This was one of my first aur packages. I'll take a look into it.

**Comment by rixx** [comment]
Seems fixed? 

```shell
$ pacman -Ql rofi-zeal-git
rofi-zeal-git /usr/
rofi-zeal-git /usr/bin/
rofi-zeal-git /usr/bin/rofi-zeal
```

**Comment by Zeioth** [comment]
PKGBUILD updated (credits to [SpotlightKid](https://aur.archlinux.org/account/SpotlightKid))
