### ISSUE TITLE
Make rofi command configurable

### ISSUE THREAD

**Issue by rixx** [Zeioth/rofi-zeal#7]
My rofi config is not in the default place, and `rofi-zeal` has a hard-coded `rofi` call, so `rofi-zeal` is completely unconfigured and basically impossible to use for me.

**Comment by Zeioth** [comment]
create script pointing to your rofi binary in `~/.local/bin` and name it rofi. That way it will be callable from terminal.

**Comment by rixx** [comment]
Sorry about this issue – I had thought rofi-zeal was more complex than it is and might already have configuration options. After opening this issue, I looked into it and decided to just vendor it into my dotfiles (with proper attribution ofc). Thank you for building it though, it's been super good and helpful!

**Comment by Zeioth** [comment]
I made to be forkeable because it would be impossible to cover all cases of use. But it's a legit feature, this can be added easity 👍
